# Generated by Django 5.2.7 on 2026-03-31 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_no', models.CharField(max_length=50, unique=True)),
                ('order_status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('karigar_assigned', 'Karigar Assigned'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('design_remarks', models.TextField(blank=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metal_type', models.CharField(max_length=10)),
                ('expected_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('metal_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('making_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('karigar_status', models.CharField(choices=[('karigar_placed', 'Karigar Placed'), ('karigar_in', 'Karigar In'), ('hallmark_placed', 'Hallmark Placed'), ('hallmarking', 'Hallmarking'), ('others', 'Others'), ('complete', 'Complete')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
