# Generated by Django 5.2.7 on 2026-04-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='decimal_precision',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='shop',
            name='default_gst_rate',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='shop',
            name='hallmark_value',
            field=models.DecimalField(decimal_places=2, default=53.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='theme',
            field=models.CharField(default='System Default', max_length=20),
        ),
    ]
