# Generated by Django 5.2.7 on 2026-03-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
